sudo: required

services:
  - docker

language: python

python:
  - 3.6

script:
  - python -m pytest -v
  - python manage.py test music_api

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh