sudo: required
language: python

python:
  - "3.6"

services:
  - docker
  - postgresql

branches:
  only:
    - master

before_script:
  - pip install docker-compose
  - docker-compose up -d --build

script:
#  - docker-compose run app sh -c "python manage.py test"
  - python -m pytest -v

after_script:
  - docker-compose down