sudo: required
language: python

python:
  - "3.6"

services:
  - docker
  - postgresql

before_script:
  - pip install docker-compose
  - docker-compose up -d --build

script:
#  - docker-compose run app sh -c "python manage.py test"
  - python -m pytest -v

after_script:
  - docker-compose down

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag back $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
  - docker tag back $DOCKER_USER/back:latest
  - docker push $DOCKER_USER/back:latest

deploy:
  provider: heroku
  api_key:
    secure: ac593baf-0fb9-45ec-8ad1-b73a166c0f7a
  app: mus-trans
  on:
    repo: coolcrazycool/music_transcription