version: "3.7"

services:
  db:
    image: postgres:13
    container_name: postgres
    volumes:
    - ./postgres_data:/var/lib/postgres/data
    env_file:
      - ./.env.prod.db
  web:
    build: .
    command: gunicorn hyper_music.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/code/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
    - media_volume:/code/media
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume: