version: "3.7"

services:
  db:
    image: postgres:13
    container_name: postgres
    volumes:
    - ./postgres_data:/var/lib/postgres/data
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 hyper_music.wsgi:application -b :8000
    volumes:
      - media_volume:/code/media
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx/
    volumes:
    - media_volume:/code/media
    - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume:
  static_volume: