# Generated by Django 3.0.7 on 2020-06-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melody',
            name='pdf',
        ),
        migrations.AddField(
            model_name='melody',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Converted', 'Converted')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf/%Y/%m/%d')),
                ('melody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_api.Melody')),
            ],
        ),
    ]
