# Generated by Django 3.0.7 on 2020-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_auto_20200620_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='melody',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
