# Generated by Django 3.0.7 on 2020-06-20 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_api', '0003_auto_20200620_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melody',
            name='name',
            field=models.CharField(default='NoName', max_length=100, verbose_name='Название мелодии'),
        ),
        migrations.AlterField(
            model_name='melody',
            name='status',
            field=models.CharField(blank=True, choices=[('Uploaded', 'Uploaded'), ('Converted', 'Converted')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
